### ISSUE TITLE
Add command for Access Group 

### ISSUE THREAD

**Issue by tetsuofukuzaki** [ibm-cloud-docs/logs-router#1]
Please add the command for Access Group on "Table 1. Command to grant IAM permissions by type of identity" such as:
```
Type of identity | Command
Access group | ibmcloud iam access-group-policy-create <accessGroupName> --roles Manager --service-name logs-router
```
https://cloud.ibm.com/docs/logs-router?topic=logs-router-tenant-iam-permissions&interface=cli#tenant-iam-permissions-cli

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  This has be resolved in this new topic: https://cloud.ibm.com/docs/logs-router?topic=logs-router-iam-permissions&interface=cli
