### ISSUE TITLE
Fix broken link in cloud logs doc

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/logs-router#2]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/logs-router?topic=logs-router-tenants-list

### What do you think needs to be updated?

This link is broken: For more information, see [Setting up IAM permissions for managing tenants](https://cloud.ibm.com/docs/logs-router?topic=logs-router-tenant-iam-permissions).

**Comment by vanadiscrawford** [comment]
Issue has been fixed. Thanks for bringing this to our attention.
