### ISSUE TITLE
Cloud Logs doc should have a page how to connect Power to Cloud Logs

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/logs-router#3]
### Which topic are you reporting about?

This page should have a section on how to connect Power to Cloud Logs
https://cloud.ibm.com/docs/logs-router?topic=logs-router-cloud_services

### What do you think needs to be updated?

See above

### Anything else?

See above

**Comment by vanadiscrawford** [comment]
Thank you for your comments. We have this as an issue to be resolved.
